#!/usr/bin/env bash
# quality-gate.sh - generated by the quality-gate skill.
# Single source of truth for this project's checks: run it locally and in CI so the
# two never drift. Hand extensions live below the marker near the end of this file.
# regenerate: python skills/quality-gate/scripts/gen_gate.py --root agent-core --typecheck-path agent_core --typecheck-path tests
#
# Usage: ./scripts/quality-gate.sh [lint|typecheck|test|coverage|all]   (default: all)
set -euo pipefail

PYTHON="${PYTHON:-python3}"
COVERAGE_SOURCE="${COVERAGE_SOURCE:-agent_core}"
COV_FAIL_UNDER="${COV_FAIL_UNDER:-95}"

log() { printf '\n\033[1m[quality-gate] %s\033[0m\n' "$1"; }

do_lint() {
  log "lint"
  "$PYTHON" -m ruff check "."
  "$PYTHON" -m ruff format --check "."
}

do_typecheck() {
  log "typecheck"
  if [ -n "${TYPECHECK_PATHS:-}" ]; then echo "quality-gate: TYPECHECK_PATHS is ignored; targets are fixed at generation time" >&2; fi
  "$PYTHON" -m mypy "agent_core"
  "$PYTHON" -m mypy "tests"
}

do_test() {
  log "test"
  "$PYTHON" -m pytest
}

do_coverage() {
  log "coverage"
  "$PYTHON" -m pytest --cov="$COVERAGE_SOURCE" --cov-branch --cov-report=term-missing --cov-fail-under="$COV_FAIL_UNDER"
}

do_all() {
  do_lint
  do_typecheck
  do_coverage
  # Hand-maintained extension hook (defined below the marker, when present).
  if declare -F do_extra >/dev/null; then
    do_extra
  fi
  log "PASS"
}

main() {
  local cmd="${1:-all}"
  case "$cmd" in
    lint) do_lint ;;
    typecheck) do_typecheck ;;
    test) do_test ;;
    coverage) do_coverage ;;
    all) do_all ;;
    *) echo "usage: $0 [lint|typecheck|test|coverage|all]" >&2; exit 2 ;;
  esac
}

# --- hand-maintained extensions below; the generator manages everything above this line ---
# Define extra gate steps here as do_extra() { ... }; `all` runs them automatically.

main "$@"
