#!/usr/bin/env python3
"""Stop hook: refuse to finish a turn leaving a committed generated artifact stale.

WHY THIS EXISTS. This repository commits several artifacts that are DERIVED from code and
guarded by a `--check` that fails CI when they drift:

    docs/matrix-coverage.md        <- tests/test_matrix_coverage.py --update
    corpora/testgen/v1/            <- scripts/gen_testgen_corpus.py --write

Each is regenerated by a command nobody remembers to run, because the edit that invalidates
it is somewhere else entirely: adding one matrix cell restales `docs/matrix-coverage.md`,
and changing a corpus generator's tie-break restales 1.2MB of JSON. The failure is always
the same shape and always found late -- in CI, one round-trip after the work was finished.

Checking at Stop is the right moment: every edit in the turn has landed, so the answer is
about the final state rather than an intermediate one, and the fix is one command away
while the context is still loaded.

ADVISORY, and deliberately so. It emits `additionalContext` and exits 0 rather than using
Stop's blocking form: a turn may legitimately end with an artifact stale (mid-refactor, or
a session that is only reading), and a hook that forced a regeneration would write to
protected paths -- `docs/matrix-coverage.md` and `corpora/**` both are -- without review.
Its job is to say so, not to decide.

Fail-OPEN and bounded: every path exits 0 and each checker gets its own timeout. Both
checks are cheap (well under a second each) and run unconditionally rather than being
gated on which files the turn touched -- a "did this turn touch it" filter would have to
model the dependency from an arbitrary edit to a derived artifact, which is exactly the
inference that goes wrong and leaves these stale in the first place.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

#: Per-checker wall clock. The corpus check regenerates 60 items (~0.2s); the matrix check
#: imports the whole test suite's cell map. Generous, and bounded so a hung checker cannot
#: hold up the end of a turn.
_TIMEOUT_SECONDS = 90

#: ``(label, argv, regenerate-with)`` for each committed artifact that has a freshness gate.
#:
#: A table rather than three inlined calls: adding the fourth artifact should be one row,
#: and every entry names the command that FIXES it -- a staleness report that does not say
#: how to fix it just moves the search cost around.
_CHECKERS: tuple[tuple[str, tuple[str, ...], str], ...] = (
    (
        "docs/matrix-coverage.md",
        ("tests/test_matrix_coverage.py", "--check"),
        "python tests/test_matrix_coverage.py --update",
    ),
    (
        "corpora/testgen/v1/",
        ("scripts/gen_testgen_corpus.py", "--check"),
        "python scripts/gen_testgen_corpus.py --write",
    ),
)

#: Deliberately NOT here: `tests/test_public_surface.py`. It has an `--update` flag but no
#: `--check` — its freshness is asserted by running the module under pytest, which is far
#: too slow for a Stop hook and is already covered by the suite. A row that shelled out to
#: pytest would make ending a turn cost a test run; a row whose `--check` did not exist
#: would silently report "fresh" for an artifact nothing examined.


def _stale(argv: tuple[str, ...]) -> bool:
    """Whether this artifact's own `--check` reports drift. False on any inability to tell."""
    script = os.path.join(_REPO_ROOT, argv[0])
    if not os.path.isfile(script):
        return False
    try:
        result = subprocess.run(
            [sys.executable, script, *argv[1:]],
            capture_output=True,
            text=True,
            timeout=_TIMEOUT_SECONDS,
            cwd=_REPO_ROOT,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False  # "cannot tell" is not "stale": never invent a finding
    return result.returncode != 0


def _findings() -> list[str]:
    return [f"{label} is stale — regenerate and commit: {fix}" for label, argv, fix in _CHECKERS if _stale(argv)]


def main() -> int:
    try:
        # A Stop hook re-entered by its own continuation would run the sweep twice; the
        # documented guard is this flag on the event.
        event = json.loads(sys.stdin.read() or "{}")
        if event.get("stop_hook_active"):
            return 0
        findings = _findings()
        if findings:
            payload = {
                "hookSpecificOutput": {
                    "hookEventName": "Stop",
                    "additionalContext": (
                        "generated artifacts are out of date; CI's freshness gates will fail:\n- "
                        + "\n- ".join(findings)
                    ),
                }
            }
            print(json.dumps(payload))
    except Exception:
        pass  # fail open: an advisory check must never block the end of a turn
    return 0


if __name__ == "__main__":
    sys.exit(main())
