"""Render a :class:`DeployConfig` into a deterministic, ShellCheck-clean ``deploy.sh``.

The script's *value* is its safety rails — strict mode, ``--dry-run``, a confirmation gate
before irreversible steps, a health-check retry loop, rollback, and structured logging — not
platform-specific deploy logic. The per-step commands are honest ``TODO`` slots the user fills
in. Output is byte-stable (no timestamps).
"""

from __future__ import annotations

from .model import DeployConfig

_HEADER = (
    "#!/usr/bin/env bash",
    "# deploy.sh - generated by the deploy skill.",
    "# Safety-railed deployment scaffold: strict mode, --dry-run, a confirmation gate before",
    "# irreversible steps, a health-check retry loop, and rollback. Fill in the `true`",
    "# placeholders (marked TODO) with your platform's commands. Secrets come from the",
    "# environment at run time - never inline them here.",
    "#",
    "# Usage: ./scripts/deploy.sh [--dry-run] [--yes] <build|release|rollback|health-check>",
    "set -euo pipefail",
)

# Static body: no interpolation, so a raw string keeps bash's own \n / \033 escapes literal.
_BODY = r"""log() { printf '\n\033[1m[deploy:%s] %s\033[0m\n' "$ENVIRONMENT" "$1"; }
die() { printf 'error: %s\n' "$1" >&2; exit 1; }

# Run a command, honouring --dry-run (prints instead of executing).
run() {
  log "$1"
  shift
  if [ "$DRY_RUN" -eq 1 ]; then
    printf 'DRY-RUN: %s\n' "$*"
  else
    "$@"
  fi
}

# Confirmation gate before irreversible actions (skipped by --yes and --dry-run).
confirm() {
  if [ "$ASSUME_YES" -eq 1 ] || [ "$DRY_RUN" -eq 1 ]; then
    return 0
  fi
  printf 'About to %s in %s. Continue? [y/N] ' "$1" "$ENVIRONMENT"
  local reply=""
  read -r reply || true
  case "$reply" in
    y | Y | yes | YES) return 0 ;;
    *) die "aborted by user" ;;
  esac
}

# Fail fast on unfilled <placeholder> values instead of deploying something surprising.
require() {
  case "$1" in
    *"<"*">"*) die "unconfigured value '$1' - set the matching environment variable" ;;
  esac
}

do_build() {
  require "$ARTIFACT"
  # TODO: replace `true` with your build command, e.g. docker build -t "$ARTIFACT" .
  run "build $ARTIFACT" true
}

do_release() {
  require "$ARTIFACT"
  confirm "release $ARTIFACT"
  # TODO: replace `true` with your release command, e.g. docker push "$ARTIFACT"
  run "release $ARTIFACT to $ENVIRONMENT" true
  do_health_check
}

do_rollback() {
  confirm "roll back $APP"
  # TODO: replace `true` with your rollback command, e.g. kubectl rollout undo deploy/"$APP"
  run "rollback $APP in $ENVIRONMENT" true
}

do_health_check() {
  require "$HEALTH_URL"
  if [ "$DRY_RUN" -eq 1 ]; then
    printf 'DRY-RUN: curl %s\n' "$HEALTH_URL"
    return 0
  fi
  log "health-check"
  local attempts="${HEALTH_ATTEMPTS:-10}"
  local i=1
  while [ "$i" -le "$attempts" ]; do
    if curl -fsS "$HEALTH_URL" >/dev/null 2>&1; then
      log "healthy"
      return 0
    fi
    printf 'health check %s/%s failed; retrying...\n' "$i" "$attempts"
    sleep "${HEALTH_INTERVAL:-3}"
    i=$((i + 1))
  done
  die "health check failed after $attempts attempts"
}

usage() {
  echo "usage: $0 [--dry-run] [--yes] <build|release|rollback|health-check>" >&2
  exit 2
}

main() {
  local cmd=""
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --dry-run) DRY_RUN=1 ;;
      --yes | -y) ASSUME_YES=1 ;;
      build | release | rollback | health-check) cmd="$1" ;;
      *) usage ;;
    esac
    shift
  done
  if [ -z "$cmd" ]; then
    usage
  fi
  case "$cmd" in
    build) do_build ;;
    release) do_release ;;
    rollback) do_rollback ;;
    health-check) do_health_check ;;
  esac
}

main "$@"
"""


def _sh_escape(value: str) -> str:
    r"""Escape a value for safe literal use inside a bash double-quoted default (``${VAR:-<here>}``).

    User-provided config (app, artifact, health URL) is interpolated as the default of a
    ``${VAR:-default}`` expansion. Without escaping, a value containing ``$`` or a backtick would
    trigger parameter/command substitution when the script runs with ``VAR`` unset, and a ``"``
    would break the string. Backslash is escaped first so the other escapes are not doubled.
    """
    out = value.replace("\\", "\\\\")
    for ch in ("$", "`", '"'):
        out = out.replace(ch, "\\" + ch)
    return out


def render_deploy(config: DeployConfig) -> str:
    """Return the full deploy-script text for ``config`` (ends with exactly one newline)."""
    variables = "\n".join(
        [
            f'APP="${{APP:-{_sh_escape(config.app)}}}"',
            f'ENVIRONMENT="${{ENVIRONMENT:-{_sh_escape(config.environment)}}}"',
            f'ARTIFACT="${{ARTIFACT:-{_sh_escape(config.artifact)}}}"',
            f'HEALTH_URL="${{HEALTH_URL:-{_sh_escape(config.health_url)}}}"',
            "DRY_RUN=0",
            "ASSUME_YES=0",
        ]
    )
    text = "\n".join(_HEADER) + "\n\n" + variables + "\n\n" + _BODY
    return text.rstrip("\n") + "\n"
