# Makefile - generated by the project-setup skill.
# Deterministic scaffold: safe to extend by hand. Targets POSIX/GNU make
# (Linux, macOS, WSL). Run `make help` for the available targets.
# regenerate: python skills/project-setup/scripts/gen_makefile.py --root . --workspace

.DEFAULT_GOAL := help
.DELETE_ON_ERROR:

PYTHON ?= python3
PIP ?= $(PYTHON) -m pip

.PHONY: help install format lint typecheck test coverage check build clean check-agent-core check-behavioral-regression check-claude-foundation check-flow-corpus check-flow-protocol check-all install-all clean-all

help: ## Show this help
	@awk 'BEGIN {FS = ":.*## "} /^[a-zA-Z0-9_-]+:.*## / {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install: ## Install the project and its dependencies
	$(PIP) install -e ".[dev]"

format: ## Auto-format the code
	$(PYTHON) -m ruff format .

lint: ## Lint (via the quality-gate script)
	./scripts/quality-gate.sh lint

typecheck: ## Type-check (via the quality-gate script)
	./scripts/quality-gate.sh typecheck

test: ## Run tests (via the quality-gate script)
	./scripts/quality-gate.sh test

coverage: ## Run tests with coverage (via the quality-gate script)
	./scripts/quality-gate.sh coverage

check: ## Run the full quality gate
	./scripts/quality-gate.sh all

build: ## Build distributables
	$(PYTHON) -m build

clean: ## Remove caches and build artifacts
	rm -rf .pytest_cache .mypy_cache .ruff_cache .coverage htmlcov build dist
	find . -type d -name '__pycache__' -prune -exec rm -rf {} +
	find . -type d -name '*.egg-info' -prune -exec rm -rf {} +

# --- workspace (monorepo) fan-out: one target per member package ---

check-agent-core: ## Run agent-core's quality checks
	$(MAKE) -C agent-core check

check-behavioral-regression: ## Run behavioral-regression's quality checks
	$(MAKE) -C behavioral-regression check

check-claude-foundation: ## Run claude-foundation's quality checks
	$(MAKE) -C claude-foundation check

check-flow-corpus: ## Run flow-corpus's quality checks
	$(MAKE) -C flow-corpus check

check-flow-protocol: ## Run flow-protocol's quality checks
	$(MAKE) -C flow-protocol check

check-all: check check-agent-core check-behavioral-regression check-claude-foundation check-flow-corpus check-flow-protocol ## Run root and every member's quality checks

install-all: install ## Install the root and every member (each via its own detected install command)
	$(MAKE) -C agent-core install
	$(MAKE) -C behavioral-regression install
	$(MAKE) -C claude-foundation install
	$(MAKE) -C flow-corpus install
	$(MAKE) -C flow-protocol install

clean-all: clean ## Clean the root and every member
	$(MAKE) -C agent-core clean
	$(MAKE) -C behavioral-regression clean
	$(MAKE) -C claude-foundation clean
	$(MAKE) -C flow-corpus clean
	$(MAKE) -C flow-protocol clean
