# Makefile - generated by the project-setup skill.
# Deterministic scaffold: safe to extend by hand. Targets POSIX/GNU make
# (Linux, macOS, WSL). Run `make help` for the available targets.

.DEFAULT_GOAL := help
.DELETE_ON_ERROR:

PYTHON ?= python3
PIP ?= $(PYTHON) -m pip
TYPECHECK_PATHS ?= src
COVERAGE_SOURCE ?= eval_harness
COV_FAIL_UNDER ?= 96

.PHONY: help install format lint typecheck test coverage check build clean

help: ## Show this help
	@awk 'BEGIN {FS = ":.*## "} /^[a-zA-Z0-9_-]+:.*## / {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install: ## Install the project and its dependencies
	$(PIP) install -e ".[dev]"

format: ## Auto-format the code
	$(PYTHON) -m ruff format .

lint: ## Lint the code
	$(PYTHON) -m ruff check .

typecheck: ## Type-check the code
	$(PYTHON) -m mypy $(TYPECHECK_PATHS)

test: ## Run the test suite
	$(PYTHON) -m pytest

coverage: ## Run tests with a coverage threshold
	$(PYTHON) -m pytest --cov=$(COVERAGE_SOURCE) --cov-branch --cov-report=term-missing --cov-fail-under=$(COV_FAIL_UNDER)

check: lint typecheck test ## Run all quality checks

build: ## Build distributables
	$(PYTHON) -m build

clean: ## Remove caches and build artifacts
	rm -rf .pytest_cache .mypy_cache .ruff_cache .coverage htmlcov build dist
	find . -type d -name '__pycache__' -prune -exec rm -rf {} +
	find . -type d -name '*.egg-info' -prune -exec rm -rf {} +
