# Makefile - generated by the project-setup skill.
# Deterministic scaffold: safe to extend by hand. Targets POSIX/GNU make
# (Linux, macOS, WSL). Run `make help` for the available targets.
# regenerate: python skills/project-setup/scripts/gen_makefile.py --root . --workspace

.DEFAULT_GOAL := help
.DELETE_ON_ERROR:

PYTHON ?= python3
PIP ?= $(PYTHON) -m pip

.PHONY: help install format lint typecheck test coverage check build clean check-agent-core check-behavioral-regression check-claude-foundation check-flow-corpus check-flow-protocol check-all install-all clean-all

help: ## Show this help
	@awk 'BEGIN {FS = ":.*## "} /^[a-zA-Z0-9_-]+:.*## / {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install: ## Install the project and its dependencies
	$(PIP) install -e ".[dev]"

format: ## Auto-format the code
	$(PYTHON) -m ruff format .

lint: ## Lint (via the quality-gate script)
	./scripts/quality-gate.sh lint

typecheck: ## Type-check (via the quality-gate script)
	./scripts/quality-gate.sh typecheck

test: ## Run tests (via the quality-gate script)
	./scripts/quality-gate.sh test

coverage: ## Run tests with coverage (via the quality-gate script)
	./scripts/quality-gate.sh coverage

check: ## Run the full quality gate
	./scripts/quality-gate.sh all

# Hand-added convenience targets (not emitted by the generator). None of them creates a
# file with its own name, so they are declared phony here -- in their own statement, so
# the generated .PHONY line above stays byte-stable for the generator's --check.
.PHONY: determinism matrix-check matrix-update

determinism: ## Prove tool-call canonicalisation is stable across interpreter processes
	@# Delegates to the test that owns this assertion rather than restating the probe here,
	@# so the two can never drift. The test spawns real subprocesses with differing
	@# PYTHONHASHSEED -- a same-process check would pass against the very bug it catches.
	python -m pytest tests/test_trajectory_contracts.py -q \
		-k "stable_across_interpreter_processes or memory_address or sets_compare_equal"

matrix-check: ## Verify docs/matrix-coverage.md matches a live regeneration (F-053)
	@# Delegates to the CLI that owns the policy (census + floors + waiver/alias hygiene).
	$(PYTHON) tests/test_matrix_coverage.py --check

matrix-update: ## Regenerate docs/matrix-coverage.md from the live registry census (F-053)
	@# Refuses to write while the matrix itself has holes -- fix the rows first.
	$(PYTHON) tests/test_matrix_coverage.py --update

.PHONY: e2e-matrix-check e2e-matrix-update invariants e2e-matrix

invariants: ## Verify charter invariants and architecture drift
	$(PYTHON) scripts/check_charter_invariants.py
	$(PYTHON) scripts/check_charter_drift.py

e2e-matrix: ## Run the full end-to-end matrix test suite
	$(PYTHON) -m pytest tests/test_e2e_matrix.py -v

e2e-matrix-check: ## Verify docs/e2e-matrix/ matches a live regeneration (ADR 0033)
	$(PYTHON) tests/test_e2e_matrix.py --check

e2e-matrix-update: ## Regenerate docs/e2e-matrix/ from artifacts/e2e-report/ (ADR 0033)
	$(PYTHON) tests/test_e2e_matrix.py --update

build: ## Build distributables
	$(PYTHON) -m build

clean: ## Remove caches and build artifacts
	rm -rf .pytest_cache .mypy_cache .ruff_cache .coverage htmlcov build dist
	find . -type d -name '__pycache__' -prune -exec rm -rf {} +
	find . -type d -name '*.egg-info' -prune -exec rm -rf {} +

# --- workspace (monorepo) fan-out: one target per member package ---

check-agent-core: ## Run agent-core's quality checks
	$(MAKE) -C agent-core check

check-behavioral-regression: ## Run behavioral-regression's quality checks
	$(MAKE) -C behavioral-regression check

check-claude-foundation: ## Run claude-foundation's quality checks
	$(MAKE) -C claude-foundation check

check-flow-corpus: ## Run flow-corpus's quality checks
	$(MAKE) -C flow-corpus check

check-flow-protocol: ## Run flow-protocol's quality checks
	$(MAKE) -C flow-protocol check

check-all: check check-agent-core check-behavioral-regression check-claude-foundation check-flow-corpus check-flow-protocol ## Run root and every member's quality checks

.PHONY: pre-pr

# Overridable: the ref regression_gate.py / repo-invariant-review compare this branch
# against, e.g. `make pre-pr PRE_PR_BASE_REF=origin/develop`. A stale local ref (as
# opposed to its remote-tracking counterpart) produces misleading findings unrelated
# to the branch under review -- `git fetch origin main:main` first if in doubt.
PRE_PR_BASE_REF ?= origin/main

pre-pr: ## Full pre-PR validation: every gate CI enforces, chained locally; accumulates failures
	@rc=0; \
	echo "[pre-pr] make check-all"; $(MAKE) check-all || { echo "[pre-pr]   FAILED: make check-all"; rc=1; }; \
	echo "[pre-pr] make invariants"; $(MAKE) invariants || { echo "[pre-pr]   FAILED: make invariants"; rc=1; }; \
	echo "[pre-pr] check_size_budget.py"; $(PYTHON) scripts/check_size_budget.py || { echo "[pre-pr]   FAILED: check_size_budget.py"; rc=1; }; \
	echo "[pre-pr] check_guard_reachability.py"; $(PYTHON) scripts/check_guard_reachability.py || { echo "[pre-pr]   FAILED: check_guard_reachability.py"; rc=1; }; \
	echo "[pre-pr] check_skill_script_drift.py"; $(PYTHON) scripts/check_skill_script_drift.py || { echo "[pre-pr]   FAILED: check_skill_script_drift.py"; rc=1; }; \
	echo "[pre-pr] check_protected_changes.py"; $(PYTHON) scripts/check_protected_changes.py || { echo "[pre-pr]   FAILED: check_protected_changes.py"; rc=1; }; \
	echo "[pre-pr] regression_gate.py --base-ref $(PRE_PR_BASE_REF)"; $(PYTHON) scripts/regression_gate.py --base-ref "$(PRE_PR_BASE_REF)" || { echo "[pre-pr]   FAILED: regression_gate.py"; rc=1; }; \
	echo "[pre-pr] validate.py --tier fast --strict-git"; $(PYTHON) scripts/validate.py --tier fast --strict-git || { echo "[pre-pr]   FAILED: validate.py"; rc=1; }; \
	echo "[pre-pr] architecture-drift-guard: drift_check.py"; $(PYTHON) skills/architecture-drift-guard/scripts/drift_check.py --manifest architecture.yaml || { echo "[pre-pr]   FAILED: drift_check.py"; rc=1; }; \
	echo "[pre-pr] architecture-drift-guard: mermaid_gen.py --check"; $(PYTHON) skills/architecture-drift-guard/scripts/mermaid_gen.py --manifest architecture.yaml --check -o architecture.mmd || { echo "[pre-pr]   FAILED: mermaid_gen.py --check"; rc=1; }; \
	echo "[pre-pr] skill_marketplace.py validate"; $(PYTHON) scripts/skill_marketplace.py validate || { echo "[pre-pr]   FAILED: skill_marketplace.py validate"; rc=1; }; \
	echo "[pre-pr] make determinism"; $(MAKE) determinism || { echo "[pre-pr]   FAILED: make determinism"; rc=1; }; \
	echo "[pre-pr] repo-invariant-review (advisory, non-blocking)"; $(PYTHON) skills/repo-invariant-review/scripts/check_invariants.py --repo . --base "$(PRE_PR_BASE_REF)" || echo "[pre-pr]   advisory findings above -- not blocking, review before pushing"; \
	if [ $$rc -ne 0 ]; then echo "[pre-pr] one or more checks FAILED -- see above"; exit 1; fi; \
	echo "[pre-pr] all checks passed"

install-all: install ## Install the root and every member (each via its own detected install command)
	$(MAKE) -C agent-core install
	$(MAKE) -C behavioral-regression install
	$(MAKE) -C claude-foundation install
	$(MAKE) -C flow-corpus install
	$(MAKE) -C flow-protocol install

clean-all: clean ## Clean the root and every member
	$(MAKE) -C agent-core clean
	$(MAKE) -C behavioral-regression clean
	$(MAKE) -C claude-foundation clean
	$(MAKE) -C flow-corpus clean
	$(MAKE) -C flow-protocol clean
