"""Render :class:`GateFacts` into a deterministic, ShellCheck-clean quality-gate script.

The emitted ``quality-gate.sh`` is the single source of truth for a project's checks: the
same script runs locally and in CI, so the two cannot drift. Output is byte-stable (no
timestamps) and uses ``set -euo pipefail`` so any failing step aborts with a non-zero exit.
Only the checks the project actually supports are emitted — nothing is fabricated.
"""

from __future__ import annotations

from .model import GateFacts

_HEADER = (
    "#!/usr/bin/env bash",
    "# quality-gate.sh - generated by the quality-gate skill.",
    "# Single source of truth for this project's checks: run it locally and in CI so the",
    "# two never drift. Safe to extend by hand.",
    "#",
    "# Usage: ./scripts/quality-gate.sh [lint|typecheck|test|coverage|all]   (default: all)",
    "set -euo pipefail",
)

# printf keeps the variable out of the format string (ShellCheck-clean, no SC2059).
_LOG = "log() { printf '\\n\\033[1m[quality-gate] %s\\033[0m\\n' \"$1\"; }"

_ORDER = ("lint", "typecheck", "test", "coverage")


def _sh_escape(value: str) -> str:
    r"""Escape a value for safe literal use inside a bash double-quoted default (``${VAR:-<here>}``).

    A detected value containing ``$``, a backtick, ``"`` or ``\`` would otherwise trigger
    parameter/command substitution when the script runs with ``VAR`` unset, or break the
    string. Backslash is escaped first so the other escapes are not doubled.
    """
    out = value.replace("\\", "\\\\")
    for ch in ("$", "`", '"'):
        out = out.replace(ch, "\\" + ch)
    return out


def _step_commands(facts: GateFacts) -> dict[str, list[str]]:
    """Ordered ``{step: [shell command lines]}`` for the steps this project supports."""
    steps: dict[str, list[str]] = {}
    if facts.has_ruff:
        steps["lint"] = ['"$PYTHON" -m ruff check .', '"$PYTHON" -m ruff format --check .']
    if facts.type_checker == "mypy":
        steps["typecheck"] = ['"$PYTHON" -m mypy "$TYPECHECK_PATHS"']
    elif facts.type_checker == "pyright":
        steps["typecheck"] = ['pyright "$TYPECHECK_PATHS"']
    if facts.has_pytest:
        steps["test"] = ['"$PYTHON" -m pytest']
    if facts.has_pytest_cov:
        steps["coverage"] = [
            '"$PYTHON" -m pytest --cov="$COVERAGE_SOURCE" --cov-branch '
            '--cov-report=term-missing --cov-fail-under="$COV_FAIL_UNDER"'
        ]
    return steps


def _variables(facts: GateFacts, steps: dict[str, list[str]]) -> list[str]:
    out = [f'PYTHON="${{PYTHON:-{_sh_escape(facts.python)}}}"']
    if "typecheck" in steps:
        out.append(f'TYPECHECK_PATHS="${{TYPECHECK_PATHS:-{_sh_escape(facts.typecheck_paths)}}}"')
    if "coverage" in steps:
        out.append(f'COVERAGE_SOURCE="${{COVERAGE_SOURCE:-{_sh_escape(facts.coverage_source)}}}"')
        out.append(f'COV_FAIL_UNDER="${{COV_FAIL_UNDER:-{facts.cov_fail_under}}}"')
    return out


def _func(name: str, body: list[str]) -> list[str]:
    return [f"do_{name}() {{", f'  log "{name}"', *[f"  {cmd}" for cmd in body], "}"]


def _do_all(steps: dict[str, list[str]]) -> list[str]:
    calls = [f"do_{n}" for n in ("lint", "typecheck") if n in steps]
    if "coverage" in steps:  # coverage runs the tests too — don't run them twice
        calls.append("do_coverage")
    elif "test" in steps:
        calls.append("do_test")
    return ["do_all() {", *[f"  {call}" for call in calls], '  log "PASS"', "}"]


def _main(steps: dict[str, list[str]]) -> list[str]:
    present = [n for n in _ORDER if n in steps]
    arms = [f"    {n}) do_{n} ;;" for n in present]
    arms.append("    all) do_all ;;")
    usage = "|".join([*present, "all"])
    arms.append(f'    *) echo "usage: $0 [{usage}]" >&2; exit 2 ;;')
    return ["main() {", '  local cmd="${1:-all}"', '  case "$cmd" in', *arms, "  esac", "}"]


def render_gate(facts: GateFacts) -> str:
    """Return the full quality-gate script text (ends with exactly one newline)."""
    steps = _step_commands(facts)
    body: list[str] = [*_HEADER, "", *_variables(facts, steps), "", _LOG, ""]
    for name in _ORDER:
        if name in steps:
            body.extend(_func(name, steps[name]))
            body.append("")
    body.extend(_do_all(steps))
    body.append("")
    body.extend(_main(steps))
    body.extend(["", 'main "$@"'])
    return "\n".join(body).rstrip("\n") + "\n"


def render_ci_snippet() -> str:
    """A minimal GitHub Actions step that runs the SAME script, keeping CI == local."""
    return (
        "# Add to your CI workflow so it runs the identical gate (local == CI):\n"
        "- name: Quality gate\n"
        "  run: ./scripts/quality-gate.sh all\n"
    )
